name = "PeakPack"
version = "1.0.0"
author = "felixer87"
hash-format = "sha1"

[[files]]
# CreativeCore
file = "mods/CreativeCore_NEOFORGE_v2.14.7_mc1.21.8.jar"
hash = "62bf3baf46a413daddfa8696a2b25b49f869da21"

[[files]]
# Mouse Tweaks
file = "mods/MouseTweaks-neoforge-mc1.21.6-2.28.jar"
hash = "c4d57d318387b608ef5230a03a6c632157438df3"

[[files]]
# PEAK Craft
file = "mods/PEAK-Craft-1.0.2.jar"
hash = "03f90126a165329b8895b3afbfeb97be4c6876c2"

[[files]]
# Player Animation Library
file = "mods/PlayerAnimationLib-1.0.12+mc1.21.8.jar"
hash = "16e7dc88a404e498e7c9e5a6b81261caa0899f38"

[[files]]
# Chat Heads
file = "mods/chat_heads-0.14.0-neoforge-1.21.6.jar"
hash = "083fd8ba010b20eaaebe21852552ed8bf158a49b"

[[files]]
# Cloth Config
file = "mods/cloth-config-19.0.147-neoforge.jar"
hash = "b3e37fef3d8bb1b7b3af75fbe47f5abbfafda562"

[[files]]
# Emotecraft
file = "mods/emotecraft-neoforge-for-MC1.21.7-3.0.0-b.build.123.jar"
hash = "b70737a511f7cb2e572f1e97fc098a0b82bc58a8"

[[files]]
# Faewulf Lib
file = "mods/faewulf_lib-neoforge-1.21.6-1.3.2.jar"
hash = "052c4806727407ad1e3e05ae9ccac8ffa3f38092"

[[files]]
# Fast IP Ping
file = "mods/fast-ip-ping-v1.0.7-mc1.21.6-neoforge.jar"
hash = "a5f82d95cc65592b7b40b57743f99c83c4fb2e0d"

[[files]]
# Happy Airships
file = "mods/happy_airships-neoforge-1.1.0.jar"
hash = "d9b3b6a2909e93c20195bd6732a3f1239e34b1cf"

[[files]]
# Lithium
file = "mods/lithium-neoforge-0.18.1+mc1.21.8.jar"
hash = "b8e673bd3d6c6b00accac53a14fdce37b266849e"

[[files]]
# Piggyback
file = "mods/piggyback-neoforge-1.21.6-1.1.0.jar"
hash = "750d02bc621a2f416842a5c4683edd237cbcf1e1"

[[files]]
# Skin Restorer
file = "mods/skinrestorer-2.4.3+1.21.6-neoforge.jar"
hash = "3ccc3b7571c7e35b7757ba3e6f32aba7bd2737a7"

[[files]]
# Sodium
file = "mods/sodium-neoforge-0.7.2+mc1.21.8.jar"
hash = "e66282d85ed0d769f3ec602297f0110e36e88c35"

[[files]]
# Voice Chat
file = "mods/voicechat-neoforge-1.21.8-2.6.6.jar"
hash = "3c9047096422d6c95e6237e18a6560ca5f0f68dc"
